# Generated by Django 5.1.4 on 2025-01-11 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='published_date',
        ),
    ]
